version: '3'

services:
  yolo-client-app:
    build: ./client
    restart: always
    links:
      - yolo-backend
    ports:
      - "3000:3000"
    stdin_open: true
    networks:
      - yolo-client-backend-bridge-network
 
  yolo-backend-app:
    build: ./backend
    restart: always
    depends_on:
      - yolo-mongodb
    ports:
      - "5000:5000"
    stdin_open: true
    volumes:
      - mongodb:/var/lib/mongodb
    environment:
      - MONGODB_URI=mongodb://yolo-mongodb:27017
    networks:
      - yolo-backend-mongodb-bridge-network
      - yolo-client-backend-bridge-network
 
  yolo-mongodb:
    build: .
    restart: always
    ports:
      - "27018:27017"
    stdin_open: true
    volumes:
      - mongodb:/var/lib/mongodb
    networks:
      - yolo-backend-mongodb-bridge-network

networks:
  yolo-backend-mongodb-bridge-network:
    driver: bridge
  yolo-client-backend-bridge-network:
    driver: bridge

volumes:
  mongodb:
