version: '3'

services:
  backend:
    image: yolo-backend-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://<username>:<password>@<cluster>/<dbname>

  client:
    image: yolo-client-app
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:5000
    depends_on:
      - backend

volumes:
  db-data:
