---
- name: Install Node.js
  apt:
    name: nodejs
    state: present

- name: Install npm
  apt:
    name: npm
    state: present

- name: Install backend dependencies
  npm:
    path: /path/to/backend
    global: no

- name: Start the backend server
  shell: |
    cd {{ app_dir }}/backend
    npm start
