# k8s-manifests/backend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: yolo
spec:
  selector:
    app: yolo-backend-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort
