# k8s-manifests/frontend-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: yolo
spec:
  type: LoadBalancer
  selector:
    app: yolo-client-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
