# k8s-manifests/frontend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: yolo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: yolo-client-app
  template:
    metadata:
      labels:
        app: yolo-client-app
    spec:
      containers:
      - name: yolo
        image: lesaigor/yolo-client-app:latest:latest
        ports:
        - containerPort: 3000
